version: "3"

services:
  namenode:
    image: longpt233/hadoop-namenode-rm:v1
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: longpt233/hadoop-datanode-nm:v1
    container_name: hadoop-slave1
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
 
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
