version: "3.9"
services:
  namenode:
    image: longpt233/hadoop-base:v1
    hostname: namenode
    ports:
      - 8088:8088
      - 8032:8032
      - 9870:9870
      - 50070:50070
      - 50075:50075
    volumes:
      - nn-data:/dfs
      - nn-conf:/opt/hadoop/etc/hadoop
    networks:
      hadoop:
        ipv4_address: 192.168.10.10
    extra_hosts:
      - "datanode: 192.168.10.12"

  datanode:
    image: longpt233/hadoop-base:v1
    hostname: datanode
    volumes:
      - dn-data:/dfs
      - dn-conf:/opt/hadoop/etc/hadoop
    networks:
      hadoop:
        ipv4_address: 192.168.10.12
    extra_hosts:
      - "namenode: 192.168.10.10"


networks:
  hadoop:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/16
          gateway: 192.168.10.1

volumes:
  nn-data:
  nn-conf:
  dn-data:
  dn-conf:

