version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch-kibana
    environment:
      - node.name=elasticsearch-kibana
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch-kibana
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./data:/usr/share/elasticsearch-kibana/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-kibana:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic 

networks:
  elastic:
    driver: bridge    